export const MAIN_PAGE = "/"
export const FAVOURITES_PAGE = "/favourites"
export const IMAGES_PAGE = "/images/:page/:limit/:type"
export const SEARCH_PAGE = "/images/:page/:limit/search"
export const NOTFOUND_PAGE = "/notFound"
